version: '3.8'

services:
  web:
    image: python:3.9-slim
    container_name: spotify_flask_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: [ "python", "app.py" ]
    ports:
      - "5001:5000" # Changed port

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Path relative to the repo root
    ports:
      - "80:80"
    depends_on:
      - web

networks:
  default:
    driver: bridge
