version: '3.8'

services:
  web:
    image: python:3.9-slim
    container_name: spotify_flask_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    environment:
      - SPOTIPY_REDIRECT_URI=http://localhost:5000/callback

  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

networks:
  default:
    driver: bridge