version: '3.8'

services:
  email-processor:
    build: .
    container_name: email_processor
    volumes:
      - .:/app
    environment:
      - IMAP_SERVER=imap.your-email-provider.com
      - SMTP_SERVER=smtp.your-email-provider.com
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    networks:
      - email_network

networks:
  email_network:
    driver: bridge
